// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package commonuser

import (
	"context"

	"github.com/otter-trade/common-protobuf/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty                         = user.Empty
	GetUserApiKeyByStrategyIdReq  = user.GetUserApiKeyByStrategyIdReq
	GetUserApiKeyByStrategyIdResp = user.GetUserApiKeyByStrategyIdResp
	UserAPIKey                    = user.UserAPIKey

	CommonUser interface {
		// -----------------------用户-----------------------
		GetUserApiKeyByStrategyId(ctx context.Context, in *GetUserApiKeyByStrategyIdReq, opts ...grpc.CallOption) (*GetUserApiKeyByStrategyIdResp, error)
	}

	defaultCommonUser struct {
		cli zrpc.Client
	}
)

func NewCommonUser(cli zrpc.Client) CommonUser {
	return &defaultCommonUser{
		cli: cli,
	}
}

// -----------------------用户-----------------------
func (m *defaultCommonUser) GetUserApiKeyByStrategyId(ctx context.Context, in *GetUserApiKeyByStrategyIdReq, opts ...grpc.CallOption) (*GetUserApiKeyByStrategyIdResp, error) {
	client := user.NewCommonUserClient(m.cli.Conn())
	return client.GetUserApiKeyByStrategyId(ctx, in, opts...)
}
